### ISSUE TITLE
Canonical URL / Redirect

### ISSUE THREAD

**Issue by tordans** [britiger/osm_address_db#19]
Is the current app at https://addresses.lorenz.lu/oad_dach/countries or at https://1011.link/oad_brb/search ?

I suggest redirecting them all to one place and then to update the github description link.

It will make it easier to bookmark, share and know the service.

**Comment by britiger** [comment]
https://addresses.lorenz.lu/ is the current app. github link changed. configure redirect of old sever later.

**Comment by britiger** [comment]
Now old instances will redirect to the new one.
