### ISSUE TITLE
Imprint is down

### ISSUE THREAD

**Issue by tordans** [britiger/osm_address_db#20]
https://addresses.lorenz.lu/oad_dach/impress show 

>Whitelabel Error Page
>This application has no explicit mapping for /error, so you are seeing this as a fallback.
>Sun Mar 31 13:50:06 CEST 2019
>There was an unexpected error (type=Not Found, status=404).
>No message available

Also, I suggest "imprint" over "impress" for the URL.

**Comment by britiger** [comment]
Already fixed in source need to deploy next time.

**Comment by britiger** [comment]
deployed
